/*
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT
 */

#include "d2ai_game_info_enums.h"

namespace d2ai {

const GameInfoEnums GameInfoEnums::NOT_DECODED{
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};

GameInfoEnums::GameInfoEnums(
        int damageTypePhysical,
        int damageTypeMagical,
        int damageTypePure,
        int damageTypeAll,
        int teamRadiant,
        int teamDire,
        int teamNeutral,
        int teamNone,
        int runeTypeInvalid,
        int runeTypeDoubleDamage,
        int runeTypeHaste,
        int runeTypeIllusion,
        int runeTypeInvisibility,
        int runeTypeRegeneration,
        int runeTypeBounty,
        int runeTypeArcane,
        int runeStatusUnknown,
        int runeStatusAvailable,
        int runeStatusMissing,
        int runeSpawnPowerup1,
        int runeSpawnPowerup2,
        int runeSpawnBounty1,
        int runeSpawnBounty2,
        int runeSpawnBounty3,
        int runeSpawnBounty4,
        int itemSlotTypeInvalid,
        int itemSlotTypeMain,
        int itemSlotTypeBackpack,
        int itemSlotTypeStash,
        int botActionTypeNone,
        int botActionTypeIdle,
        int botActionTypeMoveTo,
        int botActionTypeMoveToDirectly,
        int botActionTypeAttack,
        int botActionTypeAttackMove,
        int botActionTypeUseAbility,
        int botActionTypePickUpRune,
        int botActionTypePickUpItem,
        int botActionTypeDropItem,
        int botActionTypeShrine,
        int botActionTypeDelay,
        int courierActionBurst,
        int courierActionEnemySecretShop,
        int courierActionReturn,
        int courierActionSecretShop,
        int courierActionSideShop,
        int courierActionSideShop2,
        int courierActionTakeStashItems,
        int courierActionTakeAndTransferItems,
        int courierActionTransferItems,
        int courierStateIdle,
        int courierStateAtBase,
        int courierStateMoving,
        int courierStateDeliveringItems,
        int courierStateReturningToBase,
        int courierStateDead,
        int shopHome,
        int shopSide,
        int shopSecret,
        int shopSide2,
        int shopSecret2,
        int abilityTargetTeamNone,
        int abilityTargetTeamFriendly,
        int abilityTargetTeamEnemy,
        int abilityTargetTypeNone,
        int abilityTargetTypeHero,
        int abilityTargetTypeCreep,
        int abilityTargetTypeBuilding,
        int abilityTargetTypeCourier,
        int abilityTargetTypeOther,
        int abilityTargetTypeTree,
        int abilityTargetTypeBasic,
        int abilityTargetTypeAll,
        int laneNone,
        int laneTop,
        int laneMid,
        int laneBot)
    : damageTypePhysical(damageTypePhysical),
      damageTypeMagical(damageTypeMagical),
      damageTypePure(damageTypePure),
      damageTypeAll(damageTypeAll),
      teamRadiant(teamRadiant),
      teamDire(teamDire),
      teamNeutral(teamNeutral),
      teamNone(teamNone),
      runeTypeInvalid(runeTypeInvalid),
      runeTypeDoubleDamage(runeTypeDoubleDamage),
      runeTypeHaste(runeTypeHaste),
      runeTypeIllusion(runeTypeIllusion),
      runeTypeInvisibility(runeTypeInvisibility),
      runeTypeRegeneration(runeTypeRegeneration),
      runeTypeBounty(runeTypeBounty),
      runeTypeArcane(runeTypeArcane),
      runeStatusUnknown(runeStatusUnknown),
      runeStatusAvailable(runeStatusAvailable),
      runeStatusMissing(runeStatusMissing),
      runeSpawnPowerup1(runeSpawnPowerup1),
      runeSpawnPowerup2(runeSpawnPowerup2),
      runeSpawnBounty1(runeSpawnBounty1),
      runeSpawnBounty2(runeSpawnBounty2),
      runeSpawnBounty3(runeSpawnBounty3),
      runeSpawnBounty4(runeSpawnBounty4),
      itemSlotTypeInvalid(itemSlotTypeInvalid),
      itemSlotTypeMain(itemSlotTypeMain),
      itemSlotTypeBackpack(itemSlotTypeBackpack),
      itemSlotTypeStash(itemSlotTypeStash),
      botActionTypeNone(botActionTypeNone),
      botActionTypeIdle(botActionTypeIdle),
      botActionTypeMoveTo(botActionTypeMoveTo),
      botActionTypeMoveToDirectly(botActionTypeMoveToDirectly),
      botActionTypeAttack(botActionTypeAttack),
      botActionTypeAttackMove(botActionTypeAttackMove),
      botActionTypeUseAbility(botActionTypeUseAbility),
      botActionTypePickUpRune(botActionTypePickUpRune),
      botActionTypePickUpItem(botActionTypePickUpItem),
      botActionTypeDropItem(botActionTypeDropItem),
      botActionTypeShrine(botActionTypeShrine),
      botActionTypeDelay(botActionTypeDelay),
      courierActionBurst(courierActionBurst),
      courierActionEnemySecretShop(courierActionEnemySecretShop),
      courierActionReturn(courierActionReturn),
      courierActionSecretShop(courierActionSecretShop),
      courierActionSideShop(courierActionSideShop),
      courierActionSideShop2(courierActionSideShop2),
      courierActionTakeStashItems(courierActionTakeStashItems),
      courierActionTakeAndTransferItems(courierActionTakeAndTransferItems),
      courierActionTransferItems(courierActionTransferItems),
      courierStateIdle(courierStateIdle),
      courierStateAtBase(courierStateAtBase),
      courierStateMoving(courierStateMoving),
      courierStateDeliveringItems(courierStateDeliveringItems),
      courierStateReturningToBase(courierStateReturningToBase),
      courierStateDead(courierStateDead),
      shopHome(shopHome),
      shopSide(shopSide),
      shopSecret(shopSecret),
      shopSide2(shopSide2),
      shopSecret2(shopSecret2),
      abilityTargetTeamNone(abilityTargetTeamNone),
      abilityTargetTeamFriendly(abilityTargetTeamFriendly),
      abilityTargetTeamEnemy(abilityTargetTeamEnemy),
      abilityTargetTypeNone(abilityTargetTypeNone),
      abilityTargetTypeHero(abilityTargetTypeHero),
      abilityTargetTypeCreep(abilityTargetTypeCreep),
      abilityTargetTypeBuilding(abilityTargetTypeBuilding),
      abilityTargetTypeCourier(abilityTargetTypeCourier),
      abilityTargetTypeOther(abilityTargetTypeOther),
      abilityTargetTypeTree(abilityTargetTypeTree),
      abilityTargetTypeBasic(abilityTargetTypeBasic),
      abilityTargetTypeAll(abilityTargetTypeAll),
      laneNone(laneNone),
      laneTop(laneTop),
      laneMid(laneMid),
      laneBot(laneBot) {
}

} /* namespace d2ai */
